FROM python:3.12-slim AS base

ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONPATH="/panoctagon"

COPY --from=ghcr.io/astral-sh/uv:latest /uv /bin/uv

WORKDIR /panoctagon

COPY pyproject.toml uv.lock ./
RUN uv sync --frozen --no-dev --no-install-project

COPY panoctagon/ ./panoctagon

EXPOSE 8000

ENTRYPOINT ["uv", "run", "uvicorn", "panoctagon.api.server:app", "--host", "0.0.0.0", "--port", "8000", "--root-path", "/api"]
