FROM python:3.12-slim AS base

ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONPATH="/panoctagon" \
    DAGSTER_HOME=/panoctagon/data/dagster

COPY --from=ghcr.io/astral-sh/uv:latest /uv /bin/uv

WORKDIR /panoctagon

COPY pyproject.toml uv.lock readme.md ./
RUN uv sync --frozen --no-dev --no-install-project

COPY panoctagon/ ./panoctagon

COPY dbt_project.yml .
COPY profiles.yml .
COPY packages.yml .
COPY models/ ./models

RUN uv run dbt deps --profiles-dir .

EXPOSE 3000

ENTRYPOINT ["sh", "-c", "uv run dbt compile --profiles-dir . && uv run dagster-webserver -h 0.0.0.0 -p 3000 --path-prefix /dagster"]
