FROM python:3.12-slim AS base

ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONPATH="/panoctagon"

COPY --from=ghcr.io/astral-sh/uv:latest /uv /bin/uv

WORKDIR /panoctagon

COPY pyproject.toml uv.lock ./
RUN uv sync --frozen --no-dev --no-install-project

COPY panoctagon/ ./panoctagon
COPY gunicorn_config.py .

EXPOSE 8050

ENTRYPOINT ["uv", "run", "gunicorn", "--config", "gunicorn_config.py", "panoctagon.dashboard:server"]
