FROM python:3.12-slim AS base

ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONPATH="/panoctagon" \
    DAGSTER_HOME=/panoctagon/data/dagster

COPY --from=ghcr.io/astral-sh/uv:latest /uv /bin/uv

WORKDIR /panoctagon

COPY pyproject.toml uv.lock ./
RUN uv sync --frozen --no-dev --no-install-project

COPY panoctagon/ ./panoctagon

COPY dbt_project.yml .
COPY profiles.yml .
COPY packages.yml .
COPY dbt_packages/ ./dbt_packages
COPY target/ ./target
COPY models/ ./models

RUN uv run dbt deps --profiles-dir .

EXPOSE 3000

ENTRYPOINT ["uv", "run", "dagster-webserver", "-h", "0.0.0.0", "-p", "3000"]
