panoctagon:
  target: dev
  outputs:
    dev:
      type: sqlite
      threads: 4
      database: "panoctagon"
      schema: "main"
      schemas_and_paths:
        main: "data/panoctagon_orm.db"
      schema_directory: "data"
